"""Created makes and models tables

Revision ID: 788cee03b351
Revises: ea9803960a18
Create Date: 2024-10-26 00:28:30.244484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '788cee03b351'
down_revision = 'ea9803960a18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('makes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('make_name', sa.String(length=16), nullable=True),
    sa.Column('make_code', sa.String(length=8), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('make_code'),
    sa.UniqueConstraint('make_name')
    )
    op.create_table('models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=16), nullable=False),
    sa.Column('model_code', sa.String(length=8), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model_code'),
    sa.UniqueConstraint('model_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('models')
    op.drop_table('makes')
    # ### end Alembic commands ###
