"""made foreign key relationship not unique

Revision ID: ea9803960a18
Revises: 1e51bf029b1a
Create Date: 2024-10-23 17:08:38.881379

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea9803960a18'
down_revision = '1e51bf029b1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.drop_constraint('vehicles_user_id_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.create_unique_constraint('vehicles_user_id_key', ['user_id'])

    # ### end Alembic commands ###
